import { Source } from '../src/types.js';

export const DEFAULT_SOURCES: Source[] = [
  // 1. Monitored Publications
  {
    id: 'src-kopp-marketing',
    name: 'Olaf Kopp / Kopp Online Marketing',
    sourceType: 'publication',
    baseUrl: 'https://www.kopp-online-marketing.com/',
    feedUrl: 'https://www.kopp-online-marketing.com/feed/',
    enabled: true,
    priority: 95,
    accessMethod: 'rss',
    category: 'industry_publication',
    status: 'accessible',
    notes: 'Semantic SEO, Information Retrieval & Brand SEO thought leadership by Olaf Kopp.',
    authorOrExpert: 'Olaf Kopp'
  },
  {
    id: 'src-seroundtable',
    name: 'Search Engine Roundtable',
    sourceType: 'publication',
    baseUrl: 'https://www.seroundtable.com/',
    feedUrl: 'https://www.seroundtable.com/index.xml',
    enabled: true,
    priority: 92,
    accessMethod: 'rss',
    category: 'industry_publication',
    status: 'rss_available',
    notes: 'Fast reporting on SERP fluctuations, Google test features, unconfirmed updates and Barry Schwartz reporting.'
  },
  {
    id: 'src-sej',
    name: 'Search Engine Journal',
    sourceType: 'publication',
    baseUrl: 'https://www.searchenginejournal.com/',
    feedUrl: 'https://www.searchenginejournal.com/feed/',
    enabled: true,
    priority: 88,
    accessMethod: 'rss',
    category: 'industry_publication',
    status: 'rss_available',
    notes: 'In-depth SEO reporting, technical guides, algorithm analysis and industry developments.'
  },
  {
    id: 'src-seobythesea',
    name: 'SEO by the Sea (Patent Archive)',
    sourceType: 'publication',
    baseUrl: 'https://www.seobythesea.com/',
    feedUrl: 'https://www.seobythesea.com/feed/',
    enabled: true,
    priority: 85,
    accessMethod: 'direct_page',
    category: 'patent_analysis',
    status: 'accessible',
    notes: 'Evergreen search engine patent analysis founded by Bill Slawski. Cites historical patent mechanisms when newly relevant.'
  },

  // 2. Official Google Sources
  {
    id: 'src-google-blog',
    name: 'Google Search Central Blog',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/search/blog',
    feedUrl: 'https://developers.google.com/search/blog/rss/all.xml',
    enabled: true,
    priority: 100,
    accessMethod: 'rss',
    category: 'google_official',
    status: 'accessible',
    notes: 'Primary source for official Google Search updates, algorithm announcements, and webmaster guidance.'
  },
  {
    id: 'src-google-status-history',
    name: 'Google Search Ranking Updates History',
    sourceType: 'status_dashboard',
    baseUrl: 'https://status.search.google.com/products/rGHU1u87FJnkP6W2GwMi/history',
    enabled: true,
    priority: 100,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Confirmed core, spam, reviews, and helpful content rollouts with start/finish dates.'
  },
  {
    id: 'src-google-status-dashboard',
    name: 'Google Search Status Dashboard',
    sourceType: 'status_dashboard',
    baseUrl: 'https://status.search.google.com/',
    enabled: true,
    priority: 98,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Real-time incidents, crawling anomalies, indexing outages and service health.'
  },
  {
    id: 'src-google-ranking-systems',
    name: 'Google Search Ranking Systems Guide',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/search/docs/appearance/ranking-systems-guide',
    enabled: true,
    priority: 95,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Documentation guide for active vs retired ranking systems (e.g. Helpful content system, Passage ranking, RankBrain).'
  },
  {
    id: 'src-google-core-updates',
    name: 'Google Core Update Guidance',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/search/docs/appearance/core-updates',
    enabled: true,
    priority: 95,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Official Google advice regarding broad core updates, self-assessment questions, and recovery evaluation.'
  },
  {
    id: 'src-google-search-console-docs',
    name: 'Google Search Console Documentation',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/webmaster-tools',
    enabled: true,
    priority: 90,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'GSC feature updates, report changes, URL inspection, and performance metric definitions.'
  },
  {
    id: 'src-google-essentials',
    name: 'Google Search Essentials & Spam Policies',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/search/docs/essentials',
    enabled: true,
    priority: 92,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Technical requirements, spam policies, and key best practices for indexability.'
  },
  {
    id: 'src-google-structured-data',
    name: 'Google Structured Data Search Gallery',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/search/docs/appearance/structured-data/search-gallery',
    enabled: true,
    priority: 88,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Rich snippet schema types, required/recommended properties, and visual SERP treatments.'
  },
  {
    id: 'src-google-crawling-indexing',
    name: 'Google Crawling and Indexing Documentation',
    sourceType: 'official_doc',
    baseUrl: 'https://developers.google.com/search/docs/crawling-indexing',
    enabled: true,
    priority: 90,
    accessMethod: 'direct_page',
    category: 'google_official',
    status: 'accessible',
    notes: 'Robots.txt protocols, HTTP status code handling, JavaScript rendering, and sitemap directives.'
  },

  // 3. Google Patents Monitor
  {
    id: 'src-google-patents',
    name: 'Google Patents Search & Filings',
    sourceType: 'patent_query',
    baseUrl: 'https://patents.google.com/',
    enabled: true,
    priority: 86,
    accessMethod: 'web_search',
    category: 'patent_analysis',
    status: 'search_only',
    notes: 'Newly granted or published patent applications from Alphabet/Google LLC on IR, query fan-out, RAG, and neural rankings.',
    searchQueryTemplate: 'site:patents.google.com/patent/ "Google LLC" OR "Alphabet Inc" ("ranking" OR "information retrieval" OR "generative" OR "embeddings")'
  },

  // 4. Monitored Experts (Ethical Public Discovery Only)
  {
    id: 'src-expert-olaf-kopp',
    name: 'Olaf Kopp (Semantic SEO & IR Expert)',
    sourceType: 'expert',
    baseUrl: 'https://www.kopp-online-marketing.com/olaf-kopp-4',
    feedUrl: 'https://www.kopp-online-marketing.com/feed/',
    enabled: true,
    priority: 94,
    accessMethod: 'rss',
    category: 'expert_commentary',
    status: 'accessible',
    notes: 'Semantic search, entities, LLM retrieval mechanics, and topical authority.',
    authorOrExpert: 'Olaf Kopp',
    searchQueryTemplate: 'site:linkedin.com/posts/ "Olaf Kopp" OR site:kopp-online-marketing.com "Olaf Kopp"'
  },
  {
    id: 'src-expert-lily-ray',
    name: 'Lily Ray (Algorithm Updates & E-E-A-T)',
    sourceType: 'expert',
    baseUrl: 'https://www.linkedin.com/in/lily-ray-44755615/',
    enabled: true,
    priority: 93,
    accessMethod: 'web_search',
    category: 'expert_commentary',
    status: 'search_only',
    notes: 'Core update winners/losers, E-E-A-T audits, reputation signals, and Search Quality Rater Guidelines.',
    authorOrExpert: 'Lily Ray',
    searchQueryTemplate: 'site:linkedin.com/posts/ "Lily Ray" SEO'
  },
  {
    id: 'src-expert-steve-toth',
    name: 'Steve Toth (SEONotebook / Tactical SEO)',
    sourceType: 'expert',
    baseUrl: 'https://seonotebook.com/',
    feedUrl: 'https://seonotebook.com/feed/',
    enabled: true,
    priority: 90,
    accessMethod: 'web_search',
    category: 'expert_commentary',
    status: 'search_only',
    notes: 'Tactical SEO experiments, prompt engineering for SEO, and practical search tactics.',
    authorOrExpert: 'Steve Toth',
    searchQueryTemplate: 'site:linkedin.com/posts/ "Steve Toth" OR site:seonotebook.com'
  },
  {
    id: 'src-expert-koray-gubur',
    name: 'Koray Tuğberk Gübür (Topical Authority & Semantic SEO)',
    sourceType: 'expert',
    baseUrl: 'https://www.holisticseo.digital/',
    feedUrl: 'https://www.holisticseo.digital/feed/',
    enabled: true,
    priority: 92,
    accessMethod: 'web_search',
    category: 'expert_commentary',
    status: 'search_only',
    notes: 'Topical authority, semantic content networks, macro/micro context, and algorithmic ranking models.',
    authorOrExpert: 'Koray Tuğberk Gübür',
    searchQueryTemplate: 'site:linkedin.com/posts/ "Koray Tugberk Gubur" OR site:holisticseo.digital'
  },
  {
    id: 'src-expert-aleyda-solis',
    name: 'Aleyda Solis (SEOFOMO & International/Tech SEO)',
    sourceType: 'expert',
    baseUrl: 'https://www.aleydasolis.com/',
    feedUrl: 'https://seofomo.co/feed/',
    enabled: true,
    priority: 92,
    accessMethod: 'rss',
    category: 'expert_commentary',
    status: 'accessible',
    notes: 'SEO FOMO curation, international SEO, AI in search workflows, and technical strategies.',
    authorOrExpert: 'Aleyda Solis',
    searchQueryTemplate: 'site:linkedin.com/posts/ "Aleyda Solis" OR site:seofomo.co'
  },
  {
    id: 'src-expert-donna-rougeau',
    name: 'Donna Rougeau (Entity SEO & Knowledge Graphs)',
    sourceType: 'expert',
    baseUrl: 'https://www.linkedin.com/in/donnarougeau/',
    enabled: true,
    priority: 88,
    accessMethod: 'web_search',
    category: 'expert_commentary',
    status: 'search_only',
    notes: 'Knowledge graphs, entity reconciliation, Schema.org and semantic web indexing.',
    authorOrExpert: 'Donna Rougeau',
    searchQueryTemplate: 'site:linkedin.com/posts/ "Donna Rougeau"'
  }
];
